# Generated by Django 4.2.7 on 2023-11-20 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(blank=True, max_length=50, null=True)),
                ('nome_item', models.CharField(blank=True, max_length=50, null=True)),
                ('quantidade', models.IntegerField(blank=True, default='0', null=True)),
                ('quantidade_recebida', models.IntegerField(blank=True, default='0', null=True)),
                ('recebido_por', models.CharField(blank=True, max_length=50, null=True)),
                ('quantidade_emitida', models.IntegerField(blank=True, default='0', null=True)),
                ('emitido_por', models.CharField(blank=True, max_length=50, null=True)),
                ('emitido_para', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_telefone', models.CharField(blank=True, max_length=50, null=True)),
                ('criado_por', models.CharField(blank=True, max_length=50, null=True)),
                ('nivel_reposicao', models.IntegerField(blank=True, default='0', null=True)),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('exportar_para_CSV', models.BooleanField(default=False)),
            ],
        ),
    ]
